apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud-hero-ingress
  labels:
    app: cloud-hero
spec:
  backend:
    serviceName: cloud-hero
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-hero-service
  labels:
    app: cloud-hero
spec:
  type: NodePort
  selector:
    app: cloud-hero
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: cloud-hero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-hero-deployment
  labels:
    app: cloud-hero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-hero
  template:
    metadata:
      labels:
        app: cloud-hero
    spec:
      containers:
      - name: cloud-hero-app
        image: gcr.io/cloud-hero-preliminary-iwmat/release-v0.4
        ports:
        - containerPort: 80
